# Generated by Django 5.1.6 on 2025-02-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbranch',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='manager_name',
            field=models.CharField(default='manager name', max_length=100),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='password',
            field=models.CharField(default='********', max_length=255),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='state',
            field=models.CharField(default='state name', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
