# Generated by Django 5.1.6 on 2025-02-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0003_remove_bankbranch_address_remove_bankbranch_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heterojunction_solar_voltage', models.FloatField(blank=True, null=True)),
                ('heat_generated', models.FloatField(blank=True, null=True)),
                ('thermoelectric_voltage', models.FloatField(blank=True, null=True)),
                ('output_voltage', models.FloatField(blank=True, null=True)),
                ('max_power_generated', models.FloatField(blank=True, null=True)),
                ('load_power_consumption', models.FloatField(blank=True, null=True)),
                ('unused_power', models.FloatField(blank=True, null=True)),
                ('x_axis_direction', models.FloatField(blank=True, null=True)),
                ('z_axis_direction', models.FloatField(blank=True, null=True)),
                ('co2_level', models.FloatField(blank=True, null=True)),
                ('carbon_reduction', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BankBranch',
        ),
    ]
